### ISSUE TITLE
ESP8266 Unstable

### ISSUE THREAD

**Issue by vlw** [cotestatnt/AsyncTelegram2#2]
1. Sometimes reboots (20 times in day)
2. Sometimes lost connection until manual reboot
3. OTA 8266 cause cyclic reboot

**Comment by vlw** [comment]
https://gist.github.com/vlw/29a660f41fe6ed00729dd839b7625d93

log of crash after OTA

**Comment by vlw** [comment]
https://gist.github.com/vlw/a887076d4c2ba74c55acff7f0c1c44fe
wifi with poor internet (crash on start)

**Comment by cotestatnt** [comment]
Hi Vladimir! Thanks for your great support.
I'm experiencing same issues and my first impression is that this crashes are related to memory management.
In the last commits indeed, I've worked around variables allocation and similar points trying to optimize it.

Reverting back for example to the old commit db95b01, i was able to solve this crashes, but i'm still searching to find the root cause.
Now my plan is to re-do the steps i've done until system become instable again in order to have clean what's happening.

**Comment by vlw** [comment]
Hi Tolentino! Tested ESP8266 Ota query sample in state d7de7fb865ff34e2478ceeb7f16216bd708cf590
Now bot not responding on inline kerboard :(
![image](https://user-images.githubusercontent.com/6003820/115149915-e09a7e00-a06e-11eb-949f-3fcff6e55954.png)

**Comment by vlw** [comment]
if I start OTA update without inline button, I get Soft WDT reset
![image](https://user-images.githubusercontent.com/6003820/115150559-923aae80-a071-11eb-8a3c-e2496b581f86.png)

**Comment by vlw** [comment]
Still random reboots in 30min

**Comment by cotestatnt** [comment]
This issues is very annoying, i was not able to circumstantiate the root cause.
I've done so many tests without stable result...
Only reverting back to v1 library approach with a global HTTP rx buffer (String for the moment), seems much more stable with esp8266 (i've uploaded files in dev branch if you want try).
