### ISSUE TITLE
Why sendMessage need pass an TBMessage Object?

### ISSUE THREAD

**Issue by matheusbach** [cotestatnt/AsyncTelegram2#29]
I believe it would be much better if this had a more flexible and clear implementation.

I don't know much about programming, so I apologize in advance for my overuse of strings and possible bugs in the code, but here's an example idea to make the implementation clearer.

```
bool AsyncTelegramBot::sendTextMessage(int64_t chat_id, String text, String parse_mode = "Default", String entities = "", bool disable_web_page_preview = false, bool disable_notification = false, int32_t reply_to_message_id = 0, bool force_reply = false, bool allow_sending_without_reply = true, String reply_markup = "")
{
    if (!strlen(text.c_str()))
        return false;

    if (chat_id == 0)
        return false;

    DynamicJsonDocument root(BUFFER_BIG);
    // Backward compatibility
    root["chat_id"] = chat_id;
    root["text"] = text;

    if (parse_mode != "Default")
        if (parse_mode == "Markdown" || parse_mode == "MarkdownV2" || parse_mode == "HTML")
            root["parse_mode"] = parse_mode;

    if (disable_web_page_preview)
        root["disable_web_page_preview"] = disable_web_page_preview;

    if (disable_notification)
        root["disable_notification"] = disable_notification;

    if (reply_to_message_id != 0)
        root["reply_to_message_id"] = reply_to_message_id;

    if (allow_sending_without_reply)
        root["allow_sending_without_reply"] = allow_sending_without_reply;

    if (strlen(entities.c_str()))
    {
        StaticJsonDocument<BUFFER_MEDIUM> doc;
        deserializeJson(doc, entities);
        JsonObject myEntities = doc.as<JsonObject>();
        root["entities"] = myEntities;
    }

    if (strlen(reply_markup.c_str()) || force_reply)
    {
        StaticJsonDocument<BUFFER_MEDIUM> doc;
        deserializeJson(doc, reply_markup);
        JsonObject myKeyb = doc.as<JsonObject>();
        root["reply_markup"] = myKeyb;
        if (force_reply)
        {
            root["reply_markup"]["selective"] = true,
            root["reply_markup"]["force_reply"] = true;
        }
    }

    root.shrinkToFit();

    size_t len = measureJson(root);
    char payload[len];
    serializeJson(root, payload, len);

    debugJson(root, Serial);
    const bool result = sendCommand("sendMessage", payload);
    return result;
}
```

**Comment by cotestatnt** [comment]
Hi @matheusbach 
This mechanism originates from the fact that the library born with the principle of the **"bot responding to the user"** and not vice versa and therefore you need something to store all the information relating to the received message (user id, message text, type of message etc etc)

Subsequently, methods were also added for direct sending to a specific chat id (user or group) which obviously you must know in advance.
```
sendTo (const int64_t userid, const char * message, const char * keyboard = nullptr);
sendTo (const int64_t userid, const String & message, String keyboard = "");
```

Thanks for your suggestion, but in my opinion a function will be simpler with less parameters (even if there are default values) and all this kind of stuff it's already defined in the [struct TBMessage](https://github.com/cotestatnt/AsyncTelegram2/blob/main/src/DataStructures.h#L54) and you can easily enable or disable only when really needed.
`bool AsyncTelegramBot::sendTextMessage(int64_t chat_id, String text, String parse_mode = "Default", String entities = "", bool disable_web_page_preview = false, bool disable_notification = false, int32_t reply_to_message_id = 0, bool force_reply = false, bool allow_sending_without_reply = true, String reply_markup = "")`

In this way, if for example you need only **force_reply** option, you have to pass also the others parameter otherwise compiler will not be able to find wich parameter you are trying to pass and something as 
```
bot.sendTextMessage(123456789, "Hello World",  "Default", "", false, false, 0, true, true, "");
```
is less clear as this where you explicit declare what it's needed

```
TBMessage msg;
msg.force_reply = true;
msg.chatId = 123456789;
bot.sendMessage(msg, "Hello World");
```

**It's just a point of view off course**, but if you prefer your way, you could easily declare your own class derivated from AsyncTelegram2 and add or overload methods written in a style more comfortable respect to yours.
With the above function for example you should also set the method sendCommand as **protected** otherwise inherited class is not able to access the method.

From my side, I've already done it anyway in order to increase flexibility (will be in the next release, but edits are [already online](https://github.com/cotestatnt/AsyncTelegram2/blob/main/src/AsyncTelegram2.h#L374))
```
#include <AsyncTelegram2.h>

class myTelegramClass : AsyncTelegram2 {
  public:
    bool sendTextMessage(int64_t chat_id, String text, String parse_mode = "Default".......
```
