### ISSUE TITLE
Button with text and command

### ISSUE THREAD

**Issue by sharkyenergy** [cotestatnt/AsyncTelegram2#67]
Hello! 

I would need to add a button to a keyboard that has a text, but sends a different text back.. something like this:

  myReplyKbd.addButton("Button1", "/command1");

but this throws error.. How can this be done?

Thank you for your great work!

**Comment by cotestatnt** [comment]
Hi @sharkyenergy 
Sorry for late reply.

A Telegram **Reply Keyboard** type can't have button label different from text because you can only set the text of button with the provided API. 
You need to use an **Inline Keyboard**, but off course it will work differently.
https://core.telegram.org/bots/api#keyboardbutton
