### ISSUE TITLE
USE_CLIENTSSL what is the right choise?

### ISSUE THREAD

**Issue by joroMaser** [cotestatnt/AsyncTelegram2#73]
I saw your description[here](https://github.com/cotestatnt/AsyncTelegram2/blob/master/examples/echoBot/echoBot.ino#L12-L17)  .
But I didn't understand what is the advantage of each choice please?
I use esp32wroom

**Comment by cotestatnt** [comment]
Hi @joroMaser 
With some old "ESP32 Arduino core" release there was an issue with WiFiClientSecure which cause memory leak sometimes.
[#5781](https://github.com/espressif/arduino-esp32/issues/5781)
[#3808](https://github.com/espressif/arduino-esp32/issues/3808)

Actually this bug was fixed, so you can choice whatever you prefer as SSLClient
